database:
  host: db
  port: 5432
  name: jobhunter
  user: user
  password: password

linkedin:
  username: your_email@example.com
  password: your_password

redis:
  host: redis
  port: 6379
  password: password
